


GET http://localhost:5000/profile/00000000-0000-0000-0000-000000000000

###
GET http://localhost:5000/profile/3bb5be38-be5e-442f-83ed-08d9747d2e74


###

DELETE  http://localhost:5000/profile/2

###
GET http://localhost:5000/depot/1

###
GET http://localhost:5000/listing/1

###
GET http://localhost:5000/listing/seller/1

###

GET http://localhost:5000/transaction/1

###

GET http://localhost:5000/transaction/seller/2

###

GET http://localhost:5000/transaction/buyer/1

###

GET http://localhost:5000/transaction/search
Content-Type: application/json

{
    "FromDate" : "2021-08-02T01:01:01",
    "ToDate" : "2021-08-04T01:01:01"
}

###

POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Daves "
}

###
PUT http://localhost:5000/profile
Content-Type: application/json

{
    "id": "aa2bd762-1453-4062-e0c9-08d973914237",
    "name": "Steve"
}

###

POST http://localhost:5000/depot
Content-Type: application/json

{
    "depotId": "F",
    "displayname": "Daves",
    "profileId" : "6558ab54-d78a-404b-754d-08d9747e07f8",
    "deliveryAddress1": "Abac",
    "deliveryAddress2": "Abacus",
    "deliveryAddress3": "Abacus",
    "deliveryAddress4": "Abacus",
    "deliveryPostCode": "RAAAA",
    "billingAddress1": "Abac",
    "billingAddress2": "Abacus",
    "billingAddress3": "Abacus",
    "billingAddress4": "Abacus",
    "billingPostCode": "RAAAA",
    "contactEmail" : "mail@mb.com",
    "contactName" : "MB",
    "contactPhone" : "44121212"
}

###

PUT http://localhost:5000/depot
Content-Type: application/json

{
    "id": "f46f846a-2a5c-4363-e3da-08d966de2428",
    "depotId": "F",
    "name": "Erwfadsfdsafdsa",
    "profileId" : "fed4323c-a2ac-4b41-5f81-08d966ddde42"
}