GET http://localhost:5000/profile/2

###

DELETE  http://localhost:5000/profile/2

###
GET http://localhost:5000/depot/1

###
GET http://localhost:5000/listing/1

###
GET http://localhost:5000/listing/seller/1

###

GET http://localhost:5000/transaction/1

###

GET http://localhost:5000/transaction/seller/2

###

GET http://localhost:5000/transaction/buyer/1

###

GET http://localhost:5000/transaction/search
Content-Type: application/json

{
    "FromDate" : "2021-08-02T01:01:01",
    "ToDate" : "2021-08-04T01:01:01"
}

###

POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Alex B"
}

###
PUT http://localhost:5000/profile
Content-Type: application/json

{
    "id": "fed4323b-a2ac-4b41-5f81-08d966ddde42",
    "name": "SOmffdr"
}

###

POST http://localhost:5000/depot
Content-Type: application/json

{
    "depotId": "F",
    "name": "Daves",
    "profileId" : "fed4323b-a2ac-4b41-5f81-08d966ddde42",
    "deliveryaddress1": "Abac",
    "deliveryaddress2": "Abacus",
    "deliveryAddress3": "Abacus",
    "deliveryAddress4": "Abacus",
    "deliveryPostCode": "RAAAA"
}

###

PUT http://localhost:5000/depot
Content-Type: application/json

{
    "id": "f46f846a-2a5c-4363-e3da-08d966de2428",
    "depotId": "F",
    "name": "Erwfadsfdsafdsa",
    "profileId" : "fed4323c-a2ac-4b41-5f81-08d966ddde42"
}